name: flutter_omarchy
description: "A new Flutter package project."
version: 0.1.0
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  toml: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

 fonts:
   - family: CaskaydiaMono Nerd Font
     fonts:
       - asset: lib/fonts/CaskaydiaMonoNerdFont-Regular.ttf
       - asset: lib/fonts/CaskaydiaMonoNerdFont-Bold.ttf
         weight: 700
