name: flutter_omarchy
description: "Develop Flutter apps for Omarchy"
version: 0.1.1
homepage: https://github.com/aloisdeniel/flutter_omarchy

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  toml: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  recase: ^4.1.0
  remove_diacritic: ^0.9.0

flutter:

 fonts:
   - family: CaskaydiaMono Nerd Font Mono
     fonts:
       - asset: lib/fonts/CaskaydiaMonoNerdFontMono-Regular.ttf
         weight: 400
       - asset: lib/fonts/CaskaydiaMonoNerdFontMono-Bold.ttf
         weight: 700
       - asset: lib/fonts/CaskaydiaMonoNerdFontMono-Italic.ttf
         style: italic
